### ISSUE TITLE
[Улучшение] Добавить кнопку "Очистить очередь"

### ISSUE THREAD

**Issue by Alroniks** [bezumkin/Sendex#23]
Пишу, дабы зафиксировать. Возможно сам и пришлю фикс.

Проблема в том, что иногда, когда подписчиков много (или когда загружается список с ящиками), то некоторые ящики могут быть с ошибками и если запускать рассылку по этим ящикам, то очередь стопориться на этом письме и дальше очередь не идет. А удалить очередь нельзя (по одному тыкаться - умереть можно). 

Второй кейс - создали рассылку, создали очередь, но вовремя вспомнили об ошибке, исправили рассылку, а в очереди уже письма есть. Нужно массово удалить всю очередь и создать заново.

Нужна кнопка, которая позволит очистить очередь рассылки (или просто групповые операции)

**Comment by bezumkin** [comment]
Насколько я помню, можно выделять сразу несколько писем через Shift или Ctrl.

**Comment by bezumkin** [comment]
https://github.com/bezumkin/Sendex/pull/26
